[project]
name = "flight_sim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nacho Durante", email = "112489652+juandurante2005@users.noreply.github.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
    "pylint>=4.0.8",
    "ruff>=0.16.5",
    "scipy>=1.17.1",
]

[project.scripts]
flight_sim = "flight_sim.__main__:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
