name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      
      - name: Run Tests with Coverage
        run: |
          uv run pytest --cov=flight_sim --cov-fail-under=75
